from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from bogda_console.contracts.models import (
    DeploymentSummary,
    Page,
    PoolSnapshot,
    PowerSnapshot,
    ProjectContext,
    QueueSnapshot,
    RunDetail,
    RunFilters,
    RunResultVersionSummary,
    RunResultView,
    RunSummary,
    ScientificStatus,
    WorkerSnapshot,
)


@runtime_checkable
class PrefectQueryPort(Protocol):
    async def health(self) -> bool: ...
    async def list_runs(self, filters: RunFilters, cursor: str | None, limit: int) -> Page[RunSummary]: ...
    async def get_run(self, run_id: str) -> RunDetail: ...
    async def list_registered_deployments(self, cursor: str | None, limit: int) -> Page[DeploymentSummary]: ...
    async def get_deployment(self, deployment_id: str) -> DeploymentSummary: ...
    async def list_work_pools(self) -> list[PoolSnapshot]: ...
    async def list_work_queues(self, work_pool_name: str) -> list[QueueSnapshot]: ...
    async def list_workers(self, work_pool_name: str) -> list[WorkerSnapshot]: ...
    async def get_work_pool_concurrency(self, work_pool_name: str) -> PoolSnapshot: ...


@runtime_checkable
class PrefectCommandPort(Protocol):
    async def submit_registered_deployment(self, deployment_id: str, parameters: dict[str, Any], idempotency_key: str) -> RunSummary: ...
    async def cancel_run(self, run_id: str) -> RunSummary: ...
    async def pause_schedule(self, deployment_id: str, schedule_id: str) -> DeploymentSummary: ...
    async def resume_schedule(self, deployment_id: str, schedule_id: str) -> DeploymentSummary: ...
    async def pause_work_queue(self, queue_id: str) -> QueueSnapshot: ...
    async def resume_work_queue(self, queue_id: str) -> QueueSnapshot: ...


@runtime_checkable
class RunResultPort(Protocol):
    async def get_latest(self, run_id: str) -> RunResultView: ...
    async def list_versions(self, run_id: str, cursor: str | None, limit: int) -> Page[RunResultVersionSummary]: ...
    async def append_review(self, run_id: str, base_artifact_id: str, scientific_status: ScientificStatus, review_summary: str | None) -> RunResultView: ...


@runtime_checkable
class PowerStatusPort(Protocol):
    async def get_dorm_status(self) -> PowerSnapshot: ...


@runtime_checkable
class ProjectContextPort(Protocol):
    async def get_run_context(self, run_id: str) -> ProjectContext | None: ...
    async def get_deployment_context(self, deployment_id: str) -> ProjectContext | None: ...
