#!/usr/bin/env python3
"""diff_issues.py — Semantic comparison of issues between two evaluation runs.

Classifies each previous issue as:
- FULLY_ADDRESSED: not found in current run
- PARTIALLY_ADDRESSED: found but with reduced severity
- NOT_ADDRESSED: found with same or greater severity
- NEW: issue in current run with no match in previous

Usage:
    python diff_issues.py --current-report <path> --previous-report <path> \
        --output-dir <path>
"""

import argparse
import json
import os
from datetime import date
from pathlib import Path


def similarity(desc1, desc2):
    """Compute word-overlap similarity between two descriptions."""
    if not desc1 or not desc2:
        return 0.0
    words1 = set(desc1.lower().split()[:10])
    words2 = set(desc2.lower().split()[:10])
    if not words1 or not words2:
        return 0.0
    intersection = words1 & words2
    return len(intersection) / max(len(words1), len(words2))


def match_issues(previous_issues, current_issues):
    """Match previous issues against current, classify each."""
    results = []
    matched_current = set()

    for prev in previous_issues:
        best_score = 0.0
        best_match = None
        for ci, curr in enumerate(current_issues):
            score = similarity(
                prev.get("description", ""),
                curr.get("description", ""),
            )
            has_same_agent = prev.get("agent") == curr.get("agent")
            has_same_loc = (
                prev.get("location") and curr.get("location")
                and similarity(prev.get("location", ""), curr.get("location", "")) > 0.5
            )
            effective_score = score * (1.5 if has_same_agent else 1.0) * (1.3 if has_same_loc else 1.0)
            if effective_score > best_score:
                best_score = effective_score
                best_match = (ci, curr)

        if best_match and best_score >= 0.7:
            ci, curr = best_match
            matched_current.add(ci)
            severity_prev = severity_weight(prev.get("severity", "Minor"))
            severity_curr = severity_weight(curr.get("severity", "Minor"))

            if severity_curr >= severity_prev:
                status = "NOT_ADDRESSED"
            else:
                status = "PARTIALLY_ADDRESSED"
            results.append({
                **prev,
                "status": status,
                "status_reason": f"{prev['severity']} → {curr['severity']}" if status == "PARTIALLY_ADDRESSED" else "Same or worse severity",
            })
        else:
            results.append({
                **prev,
                "status": "FULLY_ADDRESSED",
                "status_reason": "No matching issue found in current review",
            })

    # NEW issues
    for ci, curr in enumerate(current_issues):
        if ci not in matched_current:
            results.append({
                **curr,
                "status": "NEW",
                "status_reason": "New issue not present in previous review",
            })

    return results


def severity_weight(severity):
    """Map severity string to numeric weight for comparison."""
    return {"Critical": 3, "Major": 2, "Minor": 1, "": 0}.get(severity, 0)


def generate_diff_report(results):
    """Generate markdown diff report."""
    counts = {"FULLY_ADDRESSED": 0, "PARTIALLY_ADDRESSED": 0, "NOT_ADDRESSED": 0, "NEW": 0}
    for r in results:
        counts[r["status"]] = counts.get(r["status"], 0) + 1

    lines = [
        f"# Re-Audit Diff Report",
        f"",
        f"| Status | Count |",
        f"|--------|-------|",
    ]
    for status in ["FULLY_ADDRESSED", "PARTIALLY_ADDRESSED", "NOT_ADDRESSED", "NEW"]:
        lines.append(f"| {status} | {counts.get(status, 0)} |")
    lines.append("")

    sections = {
        "NEW": "### 新增问题",
        "NOT_ADDRESSED": "### 未解决",
        "PARTIALLY_ADDRESSED": "### 部分解决",
        "FULLY_ADDRESSED": "### 已解决",
    }
    for status, header in sections.items():
        items = [r for r in results if r["status"] == status]
        if items:
            lines.append(header)
            lines.append("")
            for i, item in enumerate(items, 1):
                desc = item.get("description", "")[:100]
                agent = item.get("agent", "?")
                severity = item.get("severity", "?")
                reason = item.get("status_reason", "")
                lines.append(f"{i}. [{severity}][{agent}] {desc}")
                if reason:
                    lines.append(f"   > {reason}")
            lines.append("")

    lines.append(f"---")
    lines.append(f"*Generated by evaluate/scripts/diff_issues.py on {date.today().isoformat()}*")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Compare issues between evaluation runs")
    parser.add_argument("--current-report", required=True, help="Path to current report.json")
    parser.add_argument("--previous-report", required=True, help="Path to previous report.json")
    parser.add_argument("--output-dir", required=True, help="Where to write diff reports")
    args = parser.parse_args()

    with open(args.current_report, encoding="utf-8") as f:
        current = json.load(f)
    with open(args.previous_report, encoding="utf-8") as f:
        previous = json.load(f)

    current_issues = current.get("issues", [])
    previous_issues = previous.get("issues", [])

    results = match_issues(previous_issues, current_issues)

    # Count & report
    counts = {"FULLY_ADDRESSED": 0, "PARTIALLY_ADDRESSED": 0, "NOT_ADDRESSED": 0, "NEW": 0}
    for r in results:
        counts[r["status"]] = counts.get(r["status"], 0) + 1

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    diff_md = generate_diff_report(results)
    with open(output_dir / "reaudit_diff.md", "w", encoding="utf-8") as f:
        f.write(diff_md)

    diff_json = {
        "counts": counts,
        "results": results,
        "regenerated_at": date.today().isoformat(),
    }
    with open(output_dir / "reaudit_diff.json", "w", encoding="utf-8") as f:
        json.dump(diff_json, f, ensure_ascii=False, indent=2)

    print(f"Re-audit diff generated:")
    print(f"  FULLY_ADDRESSED: {counts.get('FULLY_ADDRESSED', 0)}")
    print(f"  PARTIALLY_ADDRESSED: {counts.get('PARTIALLY_ADDRESSED', 0)}")
    print(f"  NOT_ADDRESSED: {counts.get('NOT_ADDRESSED', 0)}")
    print(f"  NEW: {counts.get('NEW', 0)}")
    print(f"Reports: {output_dir / 'reaudit_diff.md'}, {output_dir / 'reaudit_diff.json'}")


if __name__ == "__main__":
    main()
