import { useEffect, useMemo, useState } from "react";
import { useMutation } from "@tanstack/react-query";

import { api } from "../api/client";
import type { CapabilitySnapshot, CommandReceipt, DeploymentSummary, Schemas, RunSummary } from "../api/types";
import { ModalDialog } from "./Dialogs";
import { EnvelopeErrors } from "./EnvelopeState";
import { coerceDeploymentParameters } from "../pages/InfrastructurePage";

type Props = { deployment: DeploymentSummary | null; open: boolean; capability?: CapabilitySnapshot; onClose: () => void; onSubmitted: (run: RunSummary) => void };
type RunPreparationPreview = Schemas["RunPreparationPreview"];
type RunPreparationPreviewRequest = Schemas["RunPreparationPreviewRequest"];
type Schema = { properties?: Record<string, { type?: string; title?: string; description?: string }>; required?: string[] };
const defaults = { intent: "execute" as const, requestedModelTier: "auto" as const, workload: { expectedCalls: 1, inputTokens: 1000, outputTokens: 1000, runtimeMinutes: 5 }, allowedPreferences: { allowAutoUpgrade: false, allowFlashDowngrade: true, autoResume: false, preferOffPeak: true } };

export function RunPreparation({ deployment, open, capability, onClose, onSubmitted }: Props) {
  const [parameters, setParameters] = useState<Record<string, string>>({}); const [advanced, setAdvanced] = useState(false); const [form, setForm] = useState(defaults); const [preview, setPreview] = useState<RunPreparationPreview | null>(null); const [error, setError] = useState<string | null>(null); const [idempotencyKey, setIdempotencyKey] = useState("");
  const schema = deployment?.parameterSchema as Schema | undefined; const fields = Object.entries(schema?.properties ?? {}); const enabled = capability?.canPreparePaidRun === true && capability?.canSubmitRegisteredDeployment === true;
  useEffect(() => { if (open && deployment) { setParameters({}); setAdvanced(false); setForm(defaults); setPreview(null); setError(null); setIdempotencyKey(`bogda-console-${deployment.deploymentId}-${Date.now()}`); } }, [open, deployment]);
  const request = useMemo<RunPreparationPreviewRequest>(() => ({ projectId: capability?.projectId ?? "bogda-main", ...form }), [capability?.projectId, form]);
  const previewMutation = useMutation({ mutationFn: () => api.command<RunPreparationPreview>("/api/v1/run-preparations/preview", request) });
  const submitMutation = useMutation({ mutationFn: (body: Record<string, unknown>) => api.command<CommandReceipt<RunSummary>>(`/api/v1/deployments/${deployment!.deploymentId}/runs`, body) });
  function update<K extends keyof typeof form>(key: K, value: typeof form[K]) { setForm(current => ({ ...current, [key]: value })); setPreview(null); }
  async function makePreview() { if (!deployment) return; try { const response = await previewMutation.mutateAsync(); if (!response.data) throw new Error("预览不可用"); setPreview(response.data); setError(null); } catch (e) { setError(e instanceof Error ? e.message : "预览不可用"); } }
  async function submit() { if (!preview || !deployment) return; try { const typed = coerceDeploymentParameters(parameters, schema); const response = await submitMutation.mutateAsync({ parameters: typed, idempotencyKey, runPreparationId: preview.preparationId }); if (response.data?.snapshot) { onSubmitted(response.data.snapshot); onClose(); } } catch { setError("提交未获得权威回执；没有自动重试。"); } }
  return <ModalDialog open={open} title={`准备 ${deployment?.name ?? "Deployment"}`} onClose={onClose} busy={previewMutation.isPending || submitMutation.isPending} footer={<><button type="button" className="secondary-action" data-autofocus onClick={onClose}>返回</button>{preview ? <button type="button" className="primary-action" onClick={() => void submit()} disabled={!enabled || submitMutation.isPending}>确认并提交运行</button> : <button type="button" className="primary-action" onClick={() => void makePreview()} disabled={!enabled || previewMutation.isPending}>生成服务端预览</button>}</>}>
    {!enabled && <p className="readonly-note">当前 profile 未显式开放准备/提交能力，不能执行付费运行。</p>}<div className="parameter-fields">{fields.map(([name, property]) => <label key={name}>{property.title ?? name}<input aria-label={property.title ?? name} value={parameters[name] ?? ""} required={schema?.required?.includes(name)} onChange={e => { setParameters(p => ({ ...p, [name]: e.target.value })); setPreview(null); }} /><small>{property.description ?? name}</small></label>)}</div>
    {!preview && <><label>研究意图<select aria-label="研究意图" value={form.intent} onChange={e => update("intent", e.target.value as typeof form.intent)}><option value="execute">执行</option><option value="brief">简报</option><option value="explore">探索</option><option value="decide">决策</option><option value="audit">审计</option></select></label><label>模型层级<select aria-label="模型层级" value={form.requestedModelTier} onChange={e => update("requestedModelTier", e.target.value as typeof form.requestedModelTier)}><option value="auto">Auto</option><option value="flash">Flash</option><option value="pro">Pro</option></select></label><label><input type="checkbox" aria-label="偏好低峰时段" checked={form.allowedPreferences.preferOffPeak} onChange={e => update("allowedPreferences", { ...form.allowedPreferences, preferOffPeak: e.target.checked })} />偏好低峰时段</label><button type="button" className="quiet-action" onClick={() => setAdvanced(v => !v)}>{advanced ? "收起工作量与截止时间" : "展开工作量与截止时间"}</button>{advanced && <div className="parameter-fields"><label>输入 tokens<input aria-label="输入 tokens" type="number" value={form.workload.inputTokens} onChange={e => update("workload", { ...form.workload, inputTokens: Number(e.target.value) })} /></label><label>输出 tokens<input aria-label="输出 tokens" type="number" value={form.workload.outputTokens} onChange={e => update("workload", { ...form.workload, outputTokens: Number(e.target.value) })} /></label><label>预计调用次数<input aria-label="预计调用次数" type="number" value={form.workload.expectedCalls} onChange={e => update("workload", { ...form.workload, expectedCalls: Number(e.target.value) })} /></label><label>运行分钟<input aria-label="运行分钟" type="number" value={form.workload.runtimeMinutes} onChange={e => update("workload", { ...form.workload, runtimeMinutes: Number(e.target.value) })} /></label></div>}</>}
    {preview && <section className="preview-ledger" aria-labelledby="preview-title"><h3 id="preview-title">服务端预览</h3><dl className="dialog-facts"><div><dt>有效自主模式</dt><dd>{preview.effectiveAutonomyMode}</dd></div><div><dt>实际层级</dt><dd>{preview.effectiveModelTier?.toUpperCase() ?? "—"}</dd></div><div><dt>估算</dt><dd>{preview.budget.expectedCost} CNY</dd></div><div><dt>上限</dt><dd>{preview.budget.authorizedCeiling} CNY</dd></div><div><dt>价格期</dt><dd>{preview.pricePeriod} · {preview.scheduledStart ?? "立即"}</dd></div><div><dt>Fallback</dt><dd>{preview.fallbackModelTier?.toUpperCase() ?? "—"}</dd></div></dl><p>预览来自服务端 PriceCatalog；修改输入后必须重新生成。</p></section>}{error && <p className="command-error" role="alert">{error}</p>}<EnvelopeErrors errors={[]} />
  </ModalDialog>;
}
