/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_v1_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Deployments */
        get: operations["deployments_api_v1_deployments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deployments/{deployment_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit */
        post: operations["submit_api_v1_deployments__deployment_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deployments/{deployment_id}/schedules/{schedule_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Schedule */
        post: operations["pause_schedule_api_v1_deployments__deployment_id__schedules__schedule_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deployments/{deployment_id}/schedules/{schedule_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Schedule */
        post: operations["resume_schedule_api_v1_deployments__deployment_id__schedules__schedule_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/infrastructure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Infrastructure */
        get: operations["infrastructure_api_v1_infrastructure_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_v1_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_api_v1_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Detail */
        get: operations["run_detail_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_v1_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Result */
        get: operations["result_api_v1_runs__run_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/result/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Result Versions */
        get: operations["result_versions_api_v1_runs__run_id__result_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review */
        post: operations["review_api_v1_runs__run_id__reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test/scenario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scenario */
        post: operations["scenario_api_v1_test_scenario_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-queues/{queue_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Queue */
        post: operations["pause_queue_api_v1_work_queues__queue_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-queues/{queue_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Queue */
        post: operations["resume_queue_api_v1_work_queues__queue_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiEnvelope[CapabilitySnapshot] */
        ApiEnvelope_CapabilitySnapshot_: {
            data: components["schemas"]["CapabilitySnapshot"] | null;
            /** Errors */
            errors?: components["schemas"]["ApiError"][];
            /** Sources */
            sources?: {
                [key: string]: components["schemas"]["SourceMeta"];
            };
        };
        /** ApiEnvelope[CommandReceipt[DeploymentSummary]] */
        ApiEnvelope_CommandReceipt_DeploymentSummary__: {
            data: components["schemas"]["CommandReceipt_DeploymentSummary_"] | null;
            /** Errors */
            errors?: components["schemas"]["ApiError"][];
            /** Sources */
            sources?: {
                [key: string]: components["schemas"]["SourceMeta"];
            };
        };
        /** ApiEnvelope[CommandReceipt[QueueSnapshot]] */
        ApiEnvelope_CommandReceipt_QueueSnapshot__: {
            data: components["schemas"]["CommandReceipt_QueueSnapshot_"] | null;
            /** Errors */
            errors?: components["schemas"]["ApiError"][];
            /** Sources */
            sources?: {
                [key: string]: components["schemas"]["SourceMeta"];
            };
        };
        /** ApiEnvelope[CommandReceipt[RunResultView]] */
        ApiEnvelope_CommandReceipt_RunResultView__: {
            data: components["schemas"]["CommandReceipt_RunResultView_"] | null;
            /** Errors */
            errors?: components["schemas"]["ApiError"][];
            /** Sources */
            sources?: {
                [key: string]: components["schemas"]["SourceMeta"];
            };
        };
        /** ApiEnvelope[CommandReceipt[RunSummary]] */
        ApiEnvelope_CommandReceipt_RunSummary__: {
            data: components["schemas"]["CommandReceipt_RunSummary_"] | null;
            /** Errors */
            errors?: components["schemas"]["ApiError"][];
            /** Sources */
            sources?: {
                [key: string]: components["schemas"]["SourceMeta"];
            };
        };
        /** ApiEnvelope[InfrastructureView] */
        ApiEnvelope_InfrastructureView_: {
            data: components["schemas"]["InfrastructureView"] | null;
            /** Errors */
            errors?: components["schemas"]["ApiError"][];
            /** Sources */
            sources?: {
                [key: string]: components["schemas"]["SourceMeta"];
            };
        };
        /** ApiEnvelope[OverviewSnapshot] */
        ApiEnvelope_OverviewSnapshot_: {
            data: components["schemas"]["OverviewSnapshot"] | null;
            /** Errors */
            errors?: components["schemas"]["ApiError"][];
            /** Sources */
            sources?: {
                [key: string]: components["schemas"]["SourceMeta"];
            };
        };
        /** ApiEnvelope[Page[DeploymentSummary]] */
        ApiEnvelope_Page_DeploymentSummary__: {
            data: components["schemas"]["Page_DeploymentSummary_"] | null;
            /** Errors */
            errors?: components["schemas"]["ApiError"][];
            /** Sources */
            sources?: {
                [key: string]: components["schemas"]["SourceMeta"];
            };
        };
        /** ApiEnvelope[Page[RunResultVersionSummary]] */
        ApiEnvelope_Page_RunResultVersionSummary__: {
            data: components["schemas"]["Page_RunResultVersionSummary_"] | null;
            /** Errors */
            errors?: components["schemas"]["ApiError"][];
            /** Sources */
            sources?: {
                [key: string]: components["schemas"]["SourceMeta"];
            };
        };
        /** ApiEnvelope[Page[RunSummary]] */
        ApiEnvelope_Page_RunSummary__: {
            data: components["schemas"]["Page_RunSummary_"] | null;
            /** Errors */
            errors?: components["schemas"]["ApiError"][];
            /** Sources */
            sources?: {
                [key: string]: components["schemas"]["SourceMeta"];
            };
        };
        /** ApiEnvelope[RunDetail] */
        ApiEnvelope_RunDetail_: {
            data: components["schemas"]["RunDetail"] | null;
            /** Errors */
            errors?: components["schemas"]["ApiError"][];
            /** Sources */
            sources?: {
                [key: string]: components["schemas"]["SourceMeta"];
            };
        };
        /** ApiEnvelope[RunResultView] */
        ApiEnvelope_RunResultView_: {
            data: components["schemas"]["RunResultView"] | null;
            /** Errors */
            errors?: components["schemas"]["ApiError"][];
            /** Sources */
            sources?: {
                [key: string]: components["schemas"]["SourceMeta"];
            };
        };
        /** ApiError */
        ApiError: {
            code: components["schemas"]["ApiErrorCode"];
            details?: components["schemas"]["ApiErrorDetails"] | null;
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
            /** Source */
            source: string;
        };
        /**
         * ApiErrorCode
         * @enum {string}
         */
        ApiErrorCode: "PREFECT_UNAVAILABLE" | "RUN_RESULT_UNAVAILABLE" | "POWER_UNAVAILABLE" | "PROJECT_CONTEXT_UNAVAILABLE" | "RESULT_MISSING" | "RESULT_INVALID" | "REVIEW_CONFLICT" | "RESOURCE_CHANGED" | "RESOURCE_NOT_ALLOWLISTED" | "COMMAND_NOT_APPLICABLE" | "COMMAND_REJECTED" | "COMMAND_OUTCOME_MISMATCH" | "COMMAND_OUTCOME_UNKNOWN" | "INFRASTRUCTURE_MISCONFIGURED" | "NOT_FOUND" | "VALIDATION_ERROR" | "INTERNAL_ERROR";
        /** ApiErrorDetails */
        ApiErrorDetails: {
            /** Currentresource */
            currentResource?: {
                [key: string]: unknown;
            } | null;
            /** Expected */
            expected?: unknown | null;
            /** Fields */
            fields?: {
                [key: string]: string;
            }[];
            /** Observed */
            observed?: unknown | null;
        };
        /** ArtifactRecord */
        ArtifactRecord: {
            /** Exists */
            exists: boolean;
            /** Kind */
            kind: string;
            /** Sizebytes */
            sizeBytes?: number | null;
            /** Uri */
            uri: string;
        };
        /**
         * AutonomyMode
         * @enum {string}
         */
        AutonomyMode: "manual" | "supervised" | "autonomous";
        /**
         * Availability
         * @enum {string}
         */
        Availability: "available" | "missing" | "invalid";
        /** CapabilitySnapshot */
        CapabilitySnapshot: {
            /** Cancancelrun */
            canCancelRun: boolean;
            /** Canpauseschedule */
            canPauseSchedule: boolean;
            /** Canpauseworkqueue */
            canPauseWorkQueue: boolean;
            /** Canreviewscientificresult */
            canReviewScientificResult: boolean;
            /**
             * Cansetautonomymode
             * @default false
             * @constant
             */
            canSetAutonomyMode: false;
            /** Cansubmitregistereddeployment */
            canSubmitRegisteredDeployment: boolean;
            effectiveAutonomyMode?: components["schemas"]["AutonomyMode"] | null;
            /** Profile */
            profile: string;
            /** Projectid */
            projectId: string;
        };
        /** CommandReceipt[DeploymentSummary] */
        CommandReceipt_DeploymentSummary_: {
            /**
             * Acceptedat
             * Format: date-time
             */
            acceptedAt: string;
            /** Command */
            command: string;
            /** Resourceid */
            resourceId: string;
            snapshot: components["schemas"]["DeploymentSummary"];
        };
        /** CommandReceipt[QueueSnapshot] */
        CommandReceipt_QueueSnapshot_: {
            /**
             * Acceptedat
             * Format: date-time
             */
            acceptedAt: string;
            /** Command */
            command: string;
            /** Resourceid */
            resourceId: string;
            snapshot: components["schemas"]["QueueSnapshot"];
        };
        /** CommandReceipt[RunResultView] */
        CommandReceipt_RunResultView_: {
            /**
             * Acceptedat
             * Format: date-time
             */
            acceptedAt: string;
            /** Command */
            command: string;
            /** Resourceid */
            resourceId: string;
            snapshot: components["schemas"]["RunResultView"];
        };
        /** CommandReceipt[RunSummary] */
        CommandReceipt_RunSummary_: {
            /**
             * Acceptedat
             * Format: date-time
             */
            acceptedAt: string;
            /** Command */
            command: string;
            /** Resourceid */
            resourceId: string;
            snapshot: components["schemas"]["RunSummary"];
        };
        /** DeploymentSummary */
        DeploymentSummary: {
            /** Allowlisted */
            allowlisted: boolean;
            /** Deploymentid */
            deploymentId: string;
            /** Flowname */
            flowName: string;
            /** Name */
            name: string;
            /** Parameterschema */
            parameterSchema?: {
                [key: string]: unknown;
            };
            projectContext?: components["schemas"]["ProjectContext"] | null;
            /** Schedules */
            schedules?: components["schemas"]["ScheduleSummary"][];
            /** Workpoolname */
            workPoolName?: string | null;
            /** Workqueuename */
            workQueueName?: string | null;
        };
        /**
         * ExecutionStatus
         * @enum {string}
         */
        ExecutionStatus: "Scheduled" | "Running" | "Completed" | "Failed" | "Crashed" | "Cancelled";
        /** ExpectedVersionRequest */
        ExpectedVersionRequest: {
            /** Expectedcommandversion */
            expectedCommandVersion: string;
        };
        /**
         * Freshness
         * @enum {string}
         */
        Freshness: "fresh" | "stale" | "unavailable";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InfrastructureView */
        InfrastructureView: {
            dormPower?: components["schemas"]["PowerSnapshot"] | null;
            /** Pools */
            pools?: components["schemas"]["PoolSnapshot"][] | null;
        };
        /** OverviewSnapshot */
        OverviewSnapshot: {
            /** Execution */
            execution?: {
                [key: string]: unknown;
            } | null;
            /** Infrastructure */
            infrastructure?: {
                [key: string]: components["schemas"]["PoolSnapshot"] | null;
            } | null;
            power?: components["schemas"]["PowerSnapshot"] | null;
            /** Science */
            science?: {
                [key: string]: unknown;
            } | null;
        };
        /** Page[DeploymentSummary] */
        Page_DeploymentSummary_: {
            /** Items */
            items?: components["schemas"]["DeploymentSummary"][];
            /** Nextcursor */
            nextCursor?: string | null;
        };
        /** Page[RunResultVersionSummary] */
        Page_RunResultVersionSummary_: {
            /** Items */
            items?: components["schemas"]["RunResultVersionSummary"][];
            /** Nextcursor */
            nextCursor?: string | null;
        };
        /** Page[RunSummary] */
        Page_RunSummary_: {
            /** Items */
            items?: components["schemas"]["RunSummary"][];
            /** Nextcursor */
            nextCursor?: string | null;
        };
        /** PoolSnapshot */
        PoolSnapshot: {
            /**
             * Activeslots
             * @default 0
             */
            activeSlots: number;
            /** Concurrencylimit */
            concurrencyLimit?: number | null;
            /** Ispaused */
            isPaused: boolean;
            /** Name */
            name: string;
            /** Queues */
            queues?: components["schemas"]["QueueSnapshot"][];
            /** Status */
            status: string;
            /** Workers */
            workers?: components["schemas"]["WorkerSnapshot"][];
        };
        /**
         * PowerMode
         * @enum {string}
         */
        PowerMode: "sleep" | "compute" | "gaming" | "maintenance" | "unknown";
        /** PowerSnapshot */
        PowerSnapshot: {
            /** Agentreachable */
            agentReachable: boolean | "unknown";
            /** Host */
            host: string;
            /** Lasttransitionat */
            lastTransitionAt?: string | null;
            mode: components["schemas"]["PowerMode"];
            /** Sleepinhibited */
            sleepInhibited: boolean | "unknown";
        };
        /** PrefectStateSnapshot */
        PrefectStateSnapshot: {
            /** Message */
            message?: string | null;
            /** Name */
            name: string;
            /** Terminal */
            terminal: boolean;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Type */
            type: string;
        };
        /** ProjectContext */
        ProjectContext: {
            effectiveAutonomyMode: components["schemas"]["AutonomyMode"] | null;
            /**
             * Modesource
             * @enum {string}
             */
            modeSource: "frozen-run-request" | "deployment-default" | "unavailable";
            /** Projectid */
            projectId: string;
            /**
             * Writable
             * @default false
             * @constant
             */
            writable: false;
        };
        /** QueueSnapshot */
        QueueSnapshot: {
            /** Commandversion */
            commandVersion: string;
            /** Concurrencylimit */
            concurrencyLimit?: number | null;
            /** Ispaused */
            isPaused: boolean;
            /** Name */
            name: string;
            /** Queueid */
            queueId: string;
            /** Status */
            status: string;
        };
        /** ReviewRequest */
        ReviewRequest: {
            /** Baseartifactid */
            baseArtifactId: string;
            /** Reviewsummary */
            reviewSummary?: string | null;
            scientificStatus: components["schemas"]["ScientificStatus"];
        };
        /** RunDetail */
        RunDetail: {
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            };
            projectContext?: components["schemas"]["ProjectContext"] | null;
            run: components["schemas"]["RunSummary"];
            /** Tags */
            tags?: string[];
        };
        /** RunResultVersionSummary */
        RunResultVersionSummary: {
            /** Artifactid */
            artifactId: string;
            /**
             * Availability
             * @enum {string}
             */
            availability: "available" | "invalid";
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Reviewsummary */
            reviewSummary?: string | null;
            scientificStatus?: components["schemas"]["ScientificStatus"] | null;
        };
        /** RunResultView */
        RunResultView: {
            /** Artifactcreatedat */
            artifactCreatedAt?: string | null;
            /** Artifactid */
            artifactId?: string | null;
            availability: components["schemas"]["Availability"];
            result?: components["schemas"]["ValidRunResult"] | null;
            /** Validationissues */
            validationIssues?: string[];
        };
        /** RunSummary */
        RunSummary: {
            /** Commandversion */
            commandVersion: string;
            /** Deploymentid */
            deploymentId?: string | null;
            /** Deploymentname */
            deploymentName?: string | null;
            /** Endedat */
            endedAt?: string | null;
            /** Name */
            name: string;
            /** Projectid */
            projectId?: string | null;
            /** Runid */
            runId: string;
            /** Scheduledat */
            scheduledAt?: string | null;
            scientific?: components["schemas"]["ScientificSummary"] | null;
            /** Startedat */
            startedAt?: string | null;
            state: components["schemas"]["PrefectStateSnapshot"];
            /** Workpoolname */
            workPoolName?: string | null;
            /** Workqueuename */
            workQueueName?: string | null;
        };
        /** ScenarioRequest */
        ScenarioRequest: {
            /**
             * Scenario
             * @enum {string}
             */
            scenario: "normal-active" | "sleep-queued" | "gaming-paused" | "degraded-stale" | "result-missing-invalid-conflict" | "mobile-dense";
        };
        /** ScheduleSummary */
        ScheduleSummary: {
            /** Active */
            active: boolean;
            /** Commandversion */
            commandVersion: string;
            /** Label */
            label: string;
            /** Scheduleid */
            scheduleId: string;
            /** Updatedat */
            updatedAt?: string | null;
        };
        /**
         * ScientificStatus
         * @enum {string}
         */
        ScientificStatus: "unreviewed" | "accepted" | "rejected" | "inconclusive";
        /** ScientificSummary */
        ScientificSummary: {
            /** Artifactcreatedat */
            artifactCreatedAt?: string | null;
            /** Artifactid */
            artifactId?: string | null;
            availability: components["schemas"]["Availability"];
            /** Reviewsummary */
            reviewSummary?: string | null;
            scientificStatus?: components["schemas"]["ScientificStatus"] | null;
            /** Validationissues */
            validationIssues?: string[];
        };
        /** SourceMeta */
        SourceMeta: {
            freshness: components["schemas"]["Freshness"];
            /** Lastsuccessfulat */
            lastSuccessfulAt: string | null;
            /** Observedat */
            observedAt: string | null;
            /**
             * Receivedat
             * Format: date-time
             */
            receivedAt: string;
            /** Source */
            source: string;
            sourceMode: components["schemas"]["SourceMode"];
            /** Staleafterseconds */
            staleAfterSeconds: number;
        };
        /**
         * SourceMode
         * @enum {string}
         */
        SourceMode: "real" | "mock";
        /** SubmitRequest */
        SubmitRequest: {
            /** Idempotencykey */
            idempotencyKey: string;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            };
        };
        /** ValidRunResult */
        ValidRunResult: {
            /** Attempt */
            attempt: number;
            /** Declared Artifacts */
            declared_artifacts: components["schemas"]["ArtifactRecord"][];
            execution_status: components["schemas"]["ExecutionStatus"];
            /** Executor */
            executor: string;
            /**
             * Finished At
             * Format: date-time
             */
            finished_at: string;
            /** Job Id */
            job_id: string;
            /** Review Summary */
            review_summary?: string | null;
            /** Run Id */
            run_id: string;
            /** @default unreviewed */
            scientific_status: components["schemas"]["ScientificStatus"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Summary */
            summary: string;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkerSnapshot */
        WorkerSnapshot: {
            /** Lastheartbeattime */
            lastHeartbeatTime?: string | null;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Workerid */
            workerId: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    capabilities_api_v1_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_CapabilitySnapshot_"];
                };
            };
        };
    };
    deployments_api_v1_deployments_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_Page_DeploymentSummary__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_api_v1_deployments__deployment_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_CommandReceipt_RunSummary__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_schedule_api_v1_deployments__deployment_id__schedules__schedule_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_id: string;
                schedule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpectedVersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_CommandReceipt_DeploymentSummary__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_schedule_api_v1_deployments__deployment_id__schedules__schedule_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_id: string;
                schedule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpectedVersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_CommandReceipt_DeploymentSummary__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    infrastructure_api_v1_infrastructure_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_InfrastructureView_"];
                };
            };
        };
    };
    overview_api_v1_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_OverviewSnapshot_"];
                };
            };
        };
    };
    runs_api_v1_runs_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
                executionType?: string | null;
                scientificStatus?: string | null;
                deploymentId?: string | null;
                projectId?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_Page_RunSummary__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_detail_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_RunDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_v1_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpectedVersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_CommandReceipt_RunSummary__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    result_api_v1_runs__run_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_RunResultView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    result_versions_api_v1_runs__run_id__result_versions_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_Page_RunResultVersionSummary__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_api_v1_runs__run_id__reviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_CommandReceipt_RunResultView__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scenario_api_v1_test_scenario_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_queue_api_v1_work_queues__queue_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                queue_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpectedVersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_CommandReceipt_QueueSnapshot__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_queue_api_v1_work_queues__queue_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                queue_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpectedVersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_CommandReceipt_QueueSnapshot__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
